* Changed l10 update and sync scripts to run for each active MW version * Changed scap-2 to compile binaries for each active MW version

diff --git a/scripts/l10nupdate b/scripts/l10nupdate
--- a/scripts/l10nupdate
+++ b/scripts/l10nupdate
@@ -1,21 +1,44 @@
 #!/bin/sh
+# This script belongs in /home/wikipedia/bin/.
+PATH=/bin:/usr/bin:/sbin:/usr/sbin:
+
 umask 0002
+
 echo "Starting l10nupdate at `date`."
 if svn up --ignore-externals /home/wikipedia/l10n/trunk/phase3 &&
-	svn up --ignore-externals /home/wikipedia/l10n/trunk/extensions &&
-	php /home/wikipedia/common/php/extensions/LocalisationUpdate/update.php \
-	  --wiki=aawiki \
-	  --outdir=/home/wikipedia/common/php/cache/l10n \
-	  --all \
-	  --quiet
+	svn up --ignore-externals /home/wikipedia/l10n/trunk/extensions
 then
-	echo "Completed. Syncing to Apaches"
-	/home/wikipedia/bin/sync-l10nupdate
-	echo "Clearing message blobs"
-	php /home/wikipedia/common/php/maintenance/wmf/clearMessageBlobs.php
-	echo "All done"
+	echo "SVN update completed."
 else
-	/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"; echo "FAILED";
+	/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"
+	echo "FAILED"
+	exit 1;
 fi
+
+mwDbNames=(`mwversionsinuse --dbonly`)
+if [ -z "$mwDbNames" ]; then
+	/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"
+	echo "FAILED"
+	exit 1;
+fi
+
+for mwDb in "${mwDbNames[@]}"
+do
+	if mwscript extensions/LocalisationUpdate/update.php \
+		  --wiki="$mwDb" \
+		  --outdir=/home/wikipedia/common/php/cache/l10n \
+		  --all \
+		  --quiet
+	then
+		echo "Completed. Syncing to Apaches"
+		/home/wikipedia/bin/sync-l10nupdate
+		echo "Clearing message blobs"
+		mwscript maintenance/wmf/clearMessageBlobs.php --wiki="$mwDb"
+		echo "All done"
+	else
+		/home/wikipedia/bin/dologmsg "!log LocalisationUpdate failed"
+		echo "FAILED"
+	fi
+done
 ## Apache clients should sync updates locally every X hours or at scap time
 # Not needed anymore as of 3/20/2011 --Roan
diff --git a/scripts/scap-2 b/scripts/scap-2
--- a/scripts/scap-2
+++ b/scripts/scap-2
@@ -6,35 +6,41 @@ echo -n Copying to `hostname -s`...
 if rsync -a --delete --exclude=**/.svn/lock --no-perms \
 	10.0.5.8::common/ /usr/local/apache/common-local
 then
-	echo ok
+	echo "ok"
 else
-	echo failed
+	echo "failed"
 	exit 1
 fi
 
-
-echo -n Compiling texvc...
-
-builddir=`mktemp -dt texvc-build.XXXXXXXXXX`
-if [ -z "$builddir" ]; then
-	echo "Unable to create temporary directory"
+mwVersionNums=(`mwversionsinuse`)
+if [ -z "$mwVersionNums" ]; then
+	echo "Unable to read wikiversions.db or it is empty"
 	exit 1
 fi
 
-rsync -r --exclude=.svn/ /usr/local/apache/common-local/php-1.17/math/ "$builddir"
-cd "$builddir"
-if make -f Makefile texvc >/dev/null 2>/dev/null; then
-	echo ok
-	install -d /usr/local/apache/uncommon/1.17/bin
-	install -m 755 "$builddir"/texvc /usr/local/apache/uncommon/1.17/bin
-else
-	echo failed
-	exit 1
-fi
-rm -r "$builddir"
-cd /
+for mwVerNum in "${mwVersionNums[@]}"
+do
+	echo "MediaWiki $mwVerNum:"
+	echo -n "Compiling texvc..."
+	builddir=`mktemp -dt texvc-build.XXXXXXXXXX`
+	if [ -z "$builddir" ]; then
+		echo "Unable to create temporary directory"
+		exit 1
+	fi
 
+	rsync -r --exclude=.svn/ /usr/local/apache/common-local/php-"$mwVerNum"/math/ "$builddir"
+	cd "$builddir"
+	if make -f Makefile texvc >/dev/null 2>/dev/null; then
+		echo "ok"
+		install -d /usr/local/apache/uncommon/"$mwVerNum"/bin
+		install -m 755 "$builddir"/texvc /usr/local/apache/uncommon/"$mwVerNum"/bin
+	else
+		echo "failed"
+		exit 1
+	fi
+	rm -r "$builddir"
+	cd /
+done
 
 #echo -n "Restarting apache... "
 #/usr/bin/apache-sanity-check && ( sudo /usr/sbin/apache2ctl stop; sudo killall -9 apache2;sleep 3; sudo /usr/sbin/apache2ctl start )
-
