Added possible error message

diff --git a/scripts/sync-l10nupdate b/scripts/sync-l10nupdate
--- a/scripts/sync-l10nupdate
+++ b/scripts/sync-l10nupdate
@@ -3,6 +3,11 @@
 PATH=/bin:/usr/bin:/sbin:/usr/sbin:
 MWVER="$1"
 
+if [ -z "$MWVER" ]; then
+	echo "FAILED: MediaWiki version not provided"
+	exit 1
+fi
+
 echo "Synchronizing /home/wikipedia/common/php-$MWVER/cache/l10n to /usr/local/apache/common-local/php-$MWVER/cache/l10n..."
 echo "mediawiki-installation:"
 
